[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}"}
mainnet = {key = "${ETHERSCAN_API_KEY}"}

[fmt]
line_length = 120
wrap_comments = true
